### ISSUE TITLE
module “snap-desktop-examples” can not be installed in SNAP with .nbm after successful build

### ISSUE THREAD

**Issue by bloodbaby** [senbox-org/snap-examples#2]
i have downloaded the last version 4.0.0 SNAP(Win32) from http://step.esa.int/main/download, installation is also successful. However, the .nbm file i got from building with "maven clean + package" can not be added from Tools/Plugin. Is there anything i missed? Looking forward to reply, thanks a lot.

**Comment by marpet** [comment]
Is there an error message shown or does just not work?

**Comment by bloodbaby** [comment]
well, no error meassage. nothing shows. just remain blank in the table. However, the "snap-basic-single-module" can be added succefully.

**Comment by marpet** [comment]
We are closing the issues in GitHub in favour of discussing them in the [SNAP Forum](https://forum.step.esa.int) and having the tickets in [JIRA](https://senbox.atlassian.net).
So please ask again in the forum if you have further questions.
