### ISSUE TITLE
StampsExport not writing to the folder with snappy

### ISSUE THREAD

**Issue by makovez** [senbox-org/snap-examples#9]
Hi, I have same issue explained here https://forum.step.esa.int/t/stampsexport-op-with-snappy/9645/2 

It seems like StampsExport operator with snappy creates the folder but doesen't write the export to the folder. This means that the StampsOperatorOp.java runs fine until line 121 here https://github.com/claudiaifrim/s1tbx/blob/23c6154bb5b34b57c696b319cefdd2dea9649e63/s1tbx-op-insar/src/main/java/org/esa/s1tbx/insar/gpf/StampsExportOp.java#L120 but then we don't know what happens, as I can't see any output or error too. Only thing i can see is that it creates that targetFolder 

```
prods = jpy.array(Product, 2)
prods[0] = ifg
prods[1] = coreg

stack_ifg = [ifg, coreg]

parameters = HashMap()
parameters.put('sourceProduct', prods)

parameters.put('targetFolder', out)
parameters.put('psiFormat', True)
stamps_exp = GPF.createProduct('StampsExport', parameters, stack_ifg)
```

I have tried both with stack_ifg and prods created with jpy but result doesen't change.

**Comment by marpet** [comment]
I close this issue here and reply in the forum. The forum is the better place for such discussion.
